// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "zekr": "Zekr",
  "benefit": "Benefit",
  "ta7qeeq": "Investigation",
  "read": "Read",
  "azkarRo2ya": "Azkar And Roqya",
  "azkarSubtitle": "A collection of Azkar and Roqya",
  "ta2weel": "Dream interpretation",
  "ta2weelSubtitle": "Interpret your dreams with an elite group of interpreters",
  "chats": "Chats",
  "chatsSubtitle": "Chat with interpreters",
  "tafseerRefs": "References in dream interpreting",
  "tafseerRefsSub": "Selection of trusted references in interpreting dreams",
  "welcome": "Welcome",
  "appSections": "App Sections",
  "selectSection": "Select the app section you wish to explore",
  "variousAzkar": "Other azkar",
  "mornEvenAzkar": "Morning and evening Azkar",
  "country": "Country",
  "city": "City",
  "birthdate": "Birthdate",
  "date": "Date",
  "yourJob": "Job",
  "password": "Password",
  "confirm": "Confirm",
  "createAccount": "Register",
  "login": "Login",
  "enterCode": "Enter Code",
  "codeNotReceived": "Didn't receive code?",
  "resend": "Resend",
  "enterSentCode": "Enter verification code\nsent to your email",
  "emailValidator": "Please enter your email properly",
  "passwordValidator": "Password length must be at least 8 charactars",
  "passConfirValidator": "Passwords don't match",
  "generalValidator": "This field is required",
  "incorrectValidator": "Please enter {} properly",
  "phone": "Phone",
  "name": "Username",
  "email": "Email",
  "gender": "Gender",
  "registeredAlready": "Have an account?",
  "chooseValidator": "Please choose {}",
  "yourInfo": "Your information",
  "send": "Send",
  "resetPassowrd": "Reset Password",
  "mo3aberenList": "Interpreters List",
  "enterMailToReset": "Please enter your email to send you a verification code to reset your password",
  "buyNow": "Buy now",
  "subscribedSuccessfully": "Subscribed successfully",
  "choodesPaymentMethod": "Select a payment method",
  "subscribePkg": "Subscribe to package",
  "confirmPayment": "Confirm Payment",
  "onlinePayment": "Online payment",
  "bankCards": "Visa / Master",
  "contactUs": "Contact us",
  "weAreClose": "We are near",
  "contactUsProblem": "If your're facing a problem, don't hesitate to contact us",
  "msgBody": "Message",
  "sendMsg": "Send message",
  "editProfile": "Update profile",
  "changePassword": "Change password",
  "packagesSubscriptions": "Packages and Subscriptions",
  "aboutUs": "About Us",
  "logout": "Logout",
  "choosePaymentMethod": "Please select a payment method",
  "expYears": "Exp. {year}",
  "respondIn": "Replies in {day}",
  "year": {
    "zero": "",
    "one": "{} year",
    "two": "{} year",
    "few": "{} year",
    "other": "{} years"
  },
  "day": {
    "zero": "",
    "one": "{} day",
    "two": "{} days",
    "few": "{} days",
    "other": "{} days"
  },
  "dreamRequest": "Dream interpretation request",
  "myDreams": "My Dreams",
  "dreamRequests": "Dream interpretation requests",
  "answerSent": "Answer snet successfully",
  "completeAllFields": "Please fill all required fields",
  "sendAnswer": "Send Answer",
  "notifications": "Notifications",
  "myProfile": "Account",
  "home": "Main",
  "requestAddedSuccessfully": "Request sent successfully",
  "dreamContent": "Dream content",
  "voiceRecord": "Voice record",
  "dreamSubject": "Dream subject",
  "showDreamToUsers": "Show my request for other users",
  "sendRequest": "Send Request",
  "tafseerRequester": "Applicant",
  "yearsAge": "years",
  "moreDetails": "More details",
  "estedlal": "÷nference",
  "tafseer": "Interpretation",
  "dreamDetails": "Dream details",
  "interpreter": "Interpreter",
  "requestDetails": "Request Details",
  "requestDate": "Request date",
  "requestStatus": "Status",
  "currentSubscription": "Your current Subscription",
  "remainingDreams": " {} dreams left",
  "answered": "Answered",
  "maLe": "Male",
  "feMale": "Female",
  "newDream": "Waiting for answer",
  "dataUpdated": "Your info have been updated successfully",
  "save": "Save",
  "pleaseChooseAnswer": "Please select an answer",
  "tapToRetry": "Tap to retry",
  "notFound": "No {}",
  "answerAllQuestions": "Please answer all questions",
  "ranOutOfOrders": "Sorry, You've run out of interpretation requests.",
  "pleaseLoginFirst": "Please login to continue",
  "appLanguage": "Language",
  "chooseAppLanguage": "Select Language",
  "privacyPolicy": "Terms of use",
  "loginWithYourAccount": "Login with your Azkary W Ro'yay Account",
  "skip": "Skip",
  "dontHaveAccount": "Don't have an account?",
  "rememberMe": "Remember me",
  "forgotPassword": "Forgot password?",
  "thanksForContactingUs": "Thank you for contacting us.",
  "passwordChangedSuccessfully": "Password changed successfully",
  "oldPassword": "Old password",
  "newPassword": "new password",
  "memberSince": "Member since"
};
static const Map<String,dynamic> ar = {
  "zekr": "الذكر",
  "benefit": "الفائدة",
  "ta7qeeq": "التحقيق",
  "read": "قراءة",
  "azkarRo2ya": "الأذكار والرقية",
  "azkarSubtitle": "مجموعة من الأذكار المتنوعة والرقية الشرعية",
  "ta2weel": "تأويل الرؤى",
  "ta2weelSubtitle": "فسر رؤياك مع نخبة من المعبرين المفسرين",
  "chats": "المحادثات",
  "chatsSubtitle": "محادثات مع المعبرين والمفسرين على الرؤى المختلفة",
  "tafseerRefs": "مراجع في تفسير الرؤى",
  "tafseerRefsSub": "مجموعة من المراجع الموثوقة فيتفسير الرؤى",
  "welcome": "مرحبا بك",
  "appSections": "أقسام التطبيق",
  "selectSection": "إختر القسم المراد تصفحه في التطبيق",
  "variousAzkar": "أذكار متنوعة",
  "mornEvenAzkar": "أذكار الصباح والمساء",
  "country": "الدولة",
  "city": "المدينة",
  "birthdate": "تاريخ الميلاد",
  "date": "التاريخ",
  "yourJob": "وظيفتك",
  "password": "كلمة المرور",
  "confirm": "تأكيد",
  "createAccount": "إنشاء حساب",
  "login": "تسجيل دخول",
  "enterCode": "أدخل الكود",
  "codeNotReceived": "لم يصلك الكود ؟",
  "resend": " أعد إرساله",
  "enterSentCode": "أدخل كود الدخول\nالمرسل على بريدك الالكتروني",
  "emailValidator": "من فضلك أدخل البريد بصورة صحيحة",
  "passwordValidator": "كلمة المرور يجب ألا تقل عن ٨ أحرف",
  "passConfirValidator": "كلمة المرور غير مطابقة",
  "generalValidator": "هذا الحقل مطلوب",
  "incorrectValidator": "من فضلك أدخل {} بصورة صحيحة",
  "phone": "رقم الجوال",
  "name": "إسم المستخدم",
  "email": "البريد الالكتروني",
  "gender": "الجنس",
  "registeredAlready": "لديك حساب بالفعل ؟",
  "chooseValidator": "من فضلك اختر {}",
  "yourInfo": "بياناتك",
  "send": "إرسال",
  "resetPassowrd": "إسترجاع كلمة المرور",
  "mo3aberenList": "قائمة المعبرين",
  "enterMailToReset": "أدخل البريد الإلكتروني لارسال كود إسترجاع كلمةالمرور الخاصة بك",
  "buyNow": "الشراء الآن",
  "subscribedSuccessfully": "تم الاشتراك بنجاح",
  "choodesPaymentMethod": "قم بإختيار طريقة الدفع المناسبة لاتمام الاشتراك",
  "subscribePkg": "الإشتراك في الباقة",
  "confirmPayment": "تأكيد الشراء",
  "onlinePayment": "الدفع الإلكتروني",
  "bankCards": "Visa / Master باستخدام البطاقات البنكية",
  "contactUs": "تواصل معنا",
  "weAreClose": "نحن معك عن قرب",
  "contactUsProblem": "لا تترد في التواصل معنا في حالة مواجهة أي مشكلة",
  "msgBody": "نص الرسالة",
  "sendMsg": "إرسال رسالة",
  "editProfile": "تعديل المعلومات الشخصية",
  "changePassword": "تعديل كلمة المرور",
  "packagesSubscriptions": "الباقات والاشتراكات",
  "aboutUs": "عن التطبيق",
  "logout": "تسجيل الخروج",
  "choosePaymentMethod": "قم بإختيار طريقة الدفع المناسبة لاتمام الاشتراك",
  "expYears": "خبرة {year}",
  "respondIn": "الرد خلال {day}",
  "year": {
    "zero": "",
    "one": "عام",
    "two": "عامان",
    "few": "{} أعوام",
    "many": "{} عاماً",
    "other": "{} عام"
  },
  "day": {
    "zero": "",
    "one": "يوم",
    "two": "يومان",
    "few": "{} أيام",
    "many": "{} يوماً",
    "other": "{} يوم"
  },
  "dreamRequest": "طلب تعبير رؤيا",
  "myDreams": "سجل الرؤى",
  "dreamRequests": "طلبات التأويل",
  "answerSent": "تم ارسال ردك بنجاح",
  "completeAllFields": "من افضلك اكمل الحقول المطلوبة",
  "sendAnswer": "إرسال الرد",
  "notifications": "الإشعارات",
  "myProfile": "حسابي",
  "home": "الرئيسية",
  "requestAddedSuccessfully": "تم اضافة طلبك بنجاح",
  "dreamContent": "محتوى الرؤية",
  "voiceRecord": "تسجيل صوتي",
  "dreamSubject": "موضوع الرؤيا",
  "showDreamToUsers": "أريد إظهار الرؤيا للمستخدمين",
  "sendRequest": "إرسال الطلب",
  "tafseerRequester": "طالب التفسير",
  "yearsAge": "عام",
  "moreDetails": "مزيد من التفاصيل",
  "estedlal": "وجه الإستدلال",
  "tafseer": "التعبير / التفسير",
  "dreamDetails": "تفاصيل الرؤيا",
  "interpreter": "المعبر",
  "requestDetails": "معلومات الطلب",
  "requestDate": "وقت الطلب",
  "requestStatus": "حالة الطلب",
  "currentSubscription": "باقة إشتراكك الحالية",
  "remainingDreams": "متبقي {} رؤى متوفرة",
  "answered": "تم الرد عليه",
  "maLe": "ذكر",
  "feMale": "أنثى",
  "newDream": "في انتظار الرد",
  "dataUpdated": "تم تحديث بياناتك بنجاح",
  "save": "حفظ",
  "pleaseChooseAnswer": "من فضلك اختر اجابة",
  "tapToRetry": "إضغط لإعادة المحاولة",
  "notFound": "لا توجد {}",
  "answerAllQuestions": "من فضلك أجب على كل الأسئلة",
  "ranOutOfOrders": "قد نفذت كمية الطلبات المتاحة لديك",
  "pleaseLoginFirst": "من فضلك سجل الدخول أولا",
  "appLanguage": "لغة التطبيق",
  "chooseAppLanguage": "اختر لغة التطبيق",
  "privacyPolicy": "سياسة الخصوصية",
  "dontHaveAccount": "ليس لديك حساب؟",
  "skip": "تخطي",
  "loginWithYourAccount": "سجل دخول لحسابك على أذكاري ورؤياي",
  "rememberMe": "تذكرني",
  "forgotPassword": "نسيت كلمة المرور؟",
  "thanksForContactingUs": "شكراً لتواصلكم معنا.",
  "passwordChangedSuccessfully": "تم تعديل كلمة المرور بنجاح",
  "oldPassword": "كلمةالمرور القديمة",
  "newPassword": "كلمةالمرور الجديدة",
  "memberSince": "عضو منذ"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ar": ar};
}
