// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "zekr": "Zekr",
  "benefit": "Benefit",
  "ta7qeeq": "التحقيق",
  "read": "Read",
  "azkarRo2ya": "Azkar And Roqya",
  "azkarSubtitle": "مجموعة من الأذكار المتنوعة والرقية الشرعية",
  "ta2weel": "تأويل الرؤى",
  "ta2weelSubtitle": "فسر رؤياك مع نخبة من المعبرين المفسرين",
  "chats": "Chats",
  "chatsSubtitle": "محادثات مع المعبرين والمفسرين على الرؤى المختلفة",
  "tafseerRefs": "مراجع في تفسير الرؤى",
  "tafseerRefsSub": "مجموعة من المراجع الموثوقة فيتفسير الرؤى",
  "welcome": "Welcome",
  "appSections": "App Sections",
  "selectSection": "إختر القسم المراد تصفحه في التطبيق",
  "variousAzkar": "أذكار متنوعة",
  "mornEvenAzkar": "أذكار الصباح والمساء",
  "country": "Country",
  "city": "City",
  "birthdate": "Birthdate",
  "yourJob": "Job",
  "password": "Password",
  "confirm": "Confirm",
  "createAccount": "Register",
  "login": "Login",
  "enterCode": "Enter Code",
  "codeNotReceived": "Didn't receive code?",
  "resend": "Resend",
  "enterSentCode": "أدخل كود الدخول\nالمرسل على بريدك الالكتروني",
  "emailValidator": "من فضلك أدخل البريد بصورة صحيحة",
  "passwordValidator": "كلمة المرور يجب ألا تقل عن ٨ أحرف",
  "passConfirValidator": "كلمة المرور غير مطابقة",
  "generalValidator": "هذا الحقل مطلوب",
  "incorrectValidator": "من فضلك أدخل {} بصورة صحيحة",
  "phone": "Phone",
  "name": "Username",
  "email": "Email",
  "gender": "Gender",
  "registeredAlready": "Have an account?",
  "chooseValidator": "Please choose {}",
  "yourInfo": "Your information",
  "send": "Send",
  "resetPassowrd": "Reset Password",
  "mo3aberenList": "Interpreters List",
  "enterMailToReset": "Please enter your email to send you a verification code to reset your password",
  "buyNow": "Buy now",
  "subscribedSuccessfully": "Subscribed successfully",
  "choodesPaymentMethod": "Select a payment method",
  "subscribePkg": "Subscribe to package",
  "confirmPayment": "Confirm Payment",
  "onlinePayment": "Online payment",
  "bankCards": "Visa / Master",
  "contactUs": "Contact us",
  "weAreClose": "We are near",
  "contactUsProblem": "If your're facing a problem, don't hesitate to contact us",
  "msgBody": "Message",
  "sendMsg": "Send message",
  "editProfile": "Update profile",
  "changePassword": "Change password",
  "packagesSubscriptions": "Packages and Subscriptions",
  "aboutUs": "About Us",
  "logout": "Logout",
  "choosePaymentMethod": "قم بإختيار طريقة الدفع المناسبة لاتمام الاشتراك",
  "expYears": "Exp. {} years",
  "respondIn": "Replies in {} days",
  "dreamRequest": "طلب تعبير رؤيا",
  "myDreams": "سجل الرؤى",
  "dreamRequests": "طلبات التأويل",
  "answerSent": "تم ارسال ردك بنجاح",
  "completeAllFields": "من افضلك اكمل الحقول المطلوبة",
  "sendAnswer": "إرسال الرد",
  "notifications": "الإشعارات",
  "myProfile": "حسابي",
  "home": "الرئيسية",
  "requestAddedSuccessfully": "تم اضافة طلبك بنجاح",
  "dreamContent": "محتوى الرؤية",
  "voiceRecord": "تسجيل صوتي",
  "dreamSubject": "موضوع الرؤيا",
  "showDreamToUsers": "أريد إظهار الرؤيا للمستخدمين",
  "sendRequest": "إرسال الطلب",
  "tafseerRequester": "طالب التفسير",
  "yearsAge": "عام",
  "moreDetails": "مزيد من التفاصيل",
  "estedlal": "وجه الإستدلال",
  "tafseer": "التعبير / التفسير",
  "dreamDetails": "Dream details",
  "interpreter": "Interpreter",
  "requestDetails": "Request Details",
  "requestDate": "Request date",
  "requestStatus": "Status",
  "currentSubscription": "Your current Subscription",
  "remainingDreams": " {} dreams left",
  "answered": "Answered",
  "maLe": "Male",
  "feMale": "Female",
  "newDream": "Waiting for answer",
  "dataUpdated": "Your info have been updated successfully",
  "save": "Save",
  "pleaseChooseAnswer": "Please select an answer",
  "tapToRetry": "Tap to retry",
  "notFound": "No {}",
  "answerAllQuestions": "Please answer all questions",
  "ranOutOfOrders": "قد نفذت كمية الطلبات المتاحة لديك",
  "pleaseLoginFirst": "Please login to continue"
};
static const Map<String,dynamic> ar = {
  "zekr": "الذكر",
  "benefit": "الفائدة",
  "ta7qeeq": "التحقيق",
  "read": "قراءة",
  "azkarRo2ya": "الأذكار والرقية",
  "azkarSubtitle": "مجموعة من الأذكار المتنوعة والرقية الشرعية",
  "ta2weel": "تأويل الرؤى",
  "ta2weelSubtitle": "فسر رؤياك مع نخبة من المعبرين المفسرين",
  "chats": "المحادثات",
  "chatsSubtitle": "محادثات مع المعبرين والمفسرين على الرؤى المختلفة",
  "tafseerRefs": "مراجع في تفسير الرؤى",
  "tafseerRefsSub": "مجموعة من المراجع الموثوقة فيتفسير الرؤى",
  "welcome": "مرحبا بك",
  "appSections": "أقسام التطبيق",
  "selectSection": "إختر القسم المراد تصفحه في التطبيق",
  "variousAzkar": "أذكار متنوعة",
  "mornEvenAzkar": "أذكار الصباح والمساء",
  "country": "الدولة",
  "city": "المدينة",
  "birthdate": "تاريخ الميلاد",
  "yourJob": "وظيفتك",
  "password": "كلمة المرور",
  "confirm": "تأكيد",
  "createAccount": "إنشاء حساب",
  "login": "تسجيل دخول",
  "enterCode": "أدخل الكود",
  "codeNotReceived": "لم يصلك الكود ؟",
  "resend": " أعد إرساله",
  "enterSentCode": "أدخل كود الدخول\nالمرسل على بريدك الالكتروني",
  "emailValidator": "من فضلك أدخل البريد بصورة صحيحة",
  "passwordValidator": "كلمة المرور يجب ألا تقل عن ٨ أحرف",
  "passConfirValidator": "كلمة المرور غير مطابقة",
  "generalValidator": "هذا الحقل مطلوب",
  "incorrectValidator": "من فضلك أدخل {} بصورة صحيحة",
  "phone": "رقم الجوال",
  "name": "إسم المستخدم",
  "email": "البريد الالكتروني",
  "gender": "الجنس",
  "registeredAlready": "لديك حساب بالفعل ؟",
  "chooseValidator": "من فضلك اختر {}",
  "yourInfo": "بياناتك",
  "send": "إرسال",
  "resetPassowrd": "إسترجاع كلمة المرور",
  "mo3aberenList": "قائمة المعبرين",
  "enterMailToReset": "أدخل البريد الإلكتروني لارسال كود إسترجاع كلمةالمرور الخاصة بك",
  "buyNow": "الشراء الآن",
  "subscribedSuccessfully": "تم الاشتراك بنجاح",
  "choodesPaymentMethod": "قم بإختيار طريقة الدفع المناسبة لاتمام الاشتراك",
  "subscribePkg": "الإشتراك في الباقة",
  "confirmPayment": "تأكيد الشراء",
  "onlinePayment": "الدفع الإلكتروني",
  "bankCards": "Visa / Master باستخدام البطاقات البنكية",
  "contactUs": "تواصل معنا",
  "weAreClose": "نحن معك عن قرب",
  "contactUsProblem": "لا تترد في التواصل معنا في حالة مواجهة أي مشكلة",
  "msgBody": "نص الرسالة",
  "sendMsg": "إرسال رسالة",
  "editProfile": "تعديل المعلومات الشخصية",
  "changePassword": "تعديل كلمة المرور",
  "packagesSubscriptions": "الباقات والاشتراكات",
  "aboutUs": "عن التطبيق",
  "logout": "تسجيل الخروج",
  "choosePaymentMethod": "قم بإختيار طريقة الدفع المناسبة لاتمام الاشتراك",
  "expYears": "خبرة {} أعوام",
  "respondIn": "الرد خلال {} يوم",
  "dreamRequest": "طلب تعبير رؤيا",
  "myDreams": "سجل الرؤى",
  "dreamRequests": "طلبات التأويل",
  "answerSent": "تم ارسال ردك بنجاح",
  "completeAllFields": "من افضلك اكمل الحقول المطلوبة",
  "sendAnswer": "إرسال الرد",
  "notifications": "الإشعارات",
  "myProfile": "حسابي",
  "home": "الرئيسية",
  "requestAddedSuccessfully": "تم اضافة طلبك بنجاح",
  "dreamContent": "محتوى الرؤية",
  "voiceRecord": "تسجيل صوتي",
  "dreamSubject": "موضوع الرؤيا",
  "showDreamToUsers": "أريد إظهار الرؤيا للمستخدمين",
  "sendRequest": "إرسال الطلب",
  "tafseerRequester": "طالب التفسير",
  "yearsAge": "عام",
  "moreDetails": "مزيد من التفاصيل",
  "estedlal": "وجه الإستدلال",
  "tafseer": "التعبير / التفسير",
  "dreamDetails": "تفاصيل الرؤيا",
  "interpreter": "المعبر",
  "requestDetails": "معلومات الطلب",
  "requestDate": "وقت الطلب",
  "requestStatus": "حالة الطلب",
  "currentSubscription": "باقة إشتراكك الحالية",
  "remainingDreams": "متبقي {} رؤى متوفرة",
  "answered": "تم الرد عليه",
  "maLe": "ذكر",
  "feMale": "أنثى",
  "newDream": "في انتظار الرد",
  "dataUpdated": "تم تحديث بياناتك بنجاح",
  "save": "حفظ",
  "pleaseChooseAnswer": "من فضلك اختر اجابة",
  "tapToRetry": "إضغط لإعادة المحاولة",
  "notFound": "لا توجد {}",
  "answerAllQuestions": "من فضلك أجب على كل الأسئلة",
  "ranOutOfOrders": "قد نفذت كمية الطلبات المتاحة لديك",
  "pleaseLoginFirst": "من فضلك سجل الدخول أولا"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ar": ar};
}
