#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/gulfterminal/Downloads/flutter-2.10"
export "FLUTTER_APPLICATION_PATH=/Users/gulfterminal/Desktop/Projects/dreams"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/gulfterminal/Desktop/Projects/dreams/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.1"
export "FLUTTER_BUILD_NUMBER=11"
export "EXCLUDED_ARCHS=arm64"
export "DART_DEFINES=RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/gulfterminal/Desktop/Projects/dreams/.dart_tool/package_config.json"
